### ISSUE TITLE
Get rid of the gjson fork

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-sdk-go#13]
We had to [fork gjson](https://github.com/kubewarden/gjson) to make it build with TinyGo. That was due to qjson using the `encoding/json` package.

Latest versions of TinyGo support the `encoding/json` package, hence it should be possible to just use the upstream version of gjson.

The scope of this card is to figure out if this is doable. This can be evaluated by doing the following steps:

  * Checkout one of the existing Go policies
  * `go get -u github.com/tidwall/gjson`
  * Ensure `go.mod` is changed accordingly
  * `go mod vendor`
  * Build the policy and run the e2e tests against it

**Comment by floriankoch** [comment]
@flavio  this should be fixed by https://github.com/kubewarden/go-policy-template/pull/22
