### ISSUE TITLE
Feature Request: Deprecate and archive kubewarden/gjson

### ISSUE THREAD

**Issue by viccuad** [kubewarden/policy-sdk-go#24]
### Is your feature request related to a problem?

Since merging https://github.com/kubewarden/go-policy-template/pull/24, we don't use our fork https://github.com/kubewarden/gjson.

### Solution you'd like

Update all the policies to not use our fork kubewarden/gjson but the upstream https://github.com/tidwall/gjson.
Archive our fork without deletion, as people may be consuming it on their own policies.

**Comment by flavio** [comment]
Closing:
  * The fork has been archived
  * We will update all the Go policy to use upstream gjson before tagging new releases of them. There's no need to do all them in a bulk right now
